#!/usr/bin/env sh
if [ -d "/mnt/init" ]; then
    export SHARE_PREFIX="/mnt"
fi

tty_num=$(tty | sed -e "s/.*tty\(.*\)/\1/")
export tty_num=$tty_num

# if [ -z $DISPLAY ] && [ $TTY = "/dev/tty1" ]; then
if [ -z $DISPLAY ] && [ "1" = "$tty_num" ] && [ "$(/usr/bin/whoami)" != "root" ]; then
    ${SHARE_PREFIX}/init/sway-launch
    # ${SHARE_PREFIX}/init/velox-launch
    echo "${WAYLAND_DISPLAY}" > $HOME/.wayland_display
# else
#     echo "\$tty_num = $tty_num"
fi
export DISPLAY=${WAYLAND_DISPLAY}

# if [ -d /opt/init ]; then
#     . /opt/init/env
# el
if [ -d /mnt/init ]; then
    . /mnt/init/env
fi

# . ${SHARE_PREFIX}/toolchain/env

# set ts=4 sw=4 tw=0 et :

[ -s ~/.luaver/luaver ] && . ~/.luaver/luaver

