#! /bin/sh

alias /='eval'
# bash does not recognize //
alias //='lineno="$LINENO"'

SCRIPT_NAME="functions" && export SCRIPT_NAME

case "$(type env_reset)" in *"function"*|*"alias"*) ;;
	*)
	_env_reset() {
		local env_key_name="${1:?"env_reset needs a key"}"
		local env_value="${2:?"env_reset '$1' needs a value [$lineno : $SCRIPT_NAME]"}"
		/ "[ \"\${$env_key_name-}\" = \"$env_value\" ]" || {
			# / "echo \"Original \\$\$env_key_name = \${$env_key_name-}\""
			/ "$env_key_name=\"$env_value\"" && / "export \"$env_key_name\""
		}
	}
	alias env_reset='_env_reset'
esac

# How do I tell I'm runing in a chroot?
# https://unix.stackexchange.com/questions/14345/how-do-i-tell-im-running-in-a-chroot

# No root needed. Equal means not in a chroot
# [ "$(awk '$5=="/" {print $1}' </proc/1/mountinfo)" != "$(awk '$5=="/" {print $1}' </proc/$$/mountinfo)" ]
# root permission needed
# if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
#     echo "We are chrooted!"
# else
#     echo "Business as usual"
# fi

# Try to tell I'm runing in a chroot. Equal means not in a chroot
# Not equal (contains) means in a chroot, then ignore the tmux application, etc.
case "$(type is_chrooted)" in *"function"*|*"alias"*) ;;
	*)
		_is_chrooted() {
			local being_in_chroot=0
			local root_pid="$(awk '$5 == "/" {print $1}' < /proc/1/mountinfo)"
			local pid_list="$(awk '$5 == "/" {print $1}' < /proc/$$/mountinfo)"
			local is_pid_contained=1

			case " $pid_list " in
				*" $root_pid "*) is_pid_contained=0
			esac

			[ ! -f "/proc/1/mountinfo" ] ||
				[ ! -f "/proc/$$/mountinfo" ] ||
				[ "$is_pid_contained" -ne "0" ] ||
				being_in_chroot=1

			return $being_in_chroot
		}
	alias is_chrooted='_is_chrooted'
esac

# https://unix.stackexchange.com/questions/32041/checking-if-path-contains-home-mydir-and-adding-it-if-not-all-in-a-script
# https://tldp.org/LDP/abs/html/parameter-substitution.html
# "grep -q" "$? -eq 0" could be a good solution?
prepend() {
	[ ! -z "${1:+x}" ] || return
	local key="${1}"
	# CONTAINER_VALUE="$(eval echo "\$${1}")"
	local value="${2}"
	[ -d "${value}" ] || return
	# echo "prepend \$key   = $key"
	# echo "prepend \$CONTAINER_VALUE = $(eval echo "\$${key}")"
	case ":$(eval echo "\$${key}"):" in
		*":${value}:"*) :;;
		*) eval "export $key=${value}\${$key:+\":\$$key\"}" ;;
	esac
}
# prepend PATH "/build/os"

# https://superuser.com/questions/39751/add-directory-to-path-if-its-not-already-there
# # prepend to PATH
# _path_prepend "$XDG_DATA_HOME/phpenv/bin"
#
# # prepend to MANPATH
# _path_prepend MANPATH "$XDG_DATA_HOME/shell-installer/man"
#
# # prepend to PERL5LIB
# _path_prepend PERL5LIB "$PERL_LOCAL_LIB_ROOT/lib/perl5"
#
# Features
#
#     POSIX compliant
#     Doesn't use Bash's declare -n

prepend_path() {
	if [ -n "$2" ]; then
		case ":$(eval "echo \${${1}-}"):" in
			*":$2:"*) :;;
			*) eval "export $1=$2\${$1:+\":\$$1\"}" ;;
		esac
	else
		case ":$PATH:" in
			*":$1:"*) :;;
			*) export PATH="$1${PATH:+":$PATH"}" ;;
		esac
	fi
}

append_path() {
	if [ -n "$2" ]; then
		case ":$(eval "echo \${${1}-}"):" in
			*":$2:"*) :;;
			*) eval "export $1=\${$1:+\"\$$1:\"}$2" ;;
		esac
	else
		case ":$PATH:" in
			*":$1:"*) :;;
			*) export PATH="${PATH:+"$PATH:"}$1" ;;
		esac
	fi
}

# https://unix.stackexchange.com/questions/4965/keep-duplicates-out-of-path-on-source
# Define path_append and path_prepend to add directory to target path, e.g.
# PATH, MANPATH
# Add to the end of a target path
_path_append() {
	[ ! -z "${1:+x}" ] &&
	[ -d "$2" ] || return
	local extend=":$(eval "echo \${${1}-}"):"
	# echo "\$2 = $2"
	# echo "test=${extend##*:$2:*}"
	# [ -d "$2" ] || {
	# eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" \
	# -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ||
	[ "$extend" = "::" ] && eval "export $1=$2" ||
	[ -z "${extend##*:$2:*}" ] || eval "export $1=\$$1:$2"
	# }
}
alias path_append='_path_append'

# Add to the front of a target path
_path_prepend() {
	[ ! -z "${1:+x}" ] &&
	[ -d "$2" ] || return
	local extend=":$(eval "echo \${${1}-}"):"
	# echo "\$2 = $2"
	# echo "test=${extend##*:$2:*}"
	# [ ! -d "$2" ] || {
	# eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" \
	# -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ||
	[ "$extend" = "::" ] && eval "export $1=$2" ||
	[ -z "${extend##*:$2:*}" ] || eval "export $1=$2:\$$1"
	# }
}
alias path_prepend='_path_prepend'
