#!/bin/sh

echo "Entered tty: $tty_num"

# https://www.reddit.com/r/voidlinux/comments/mor7n5/getting_libseat_errors_when_starting_sway/
[ -n "${WAYLAND_CONFIG_HOME:+x}" ] ||
WAYLAND_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/wayland"
export WAYLAND_CONFIG_HOME

# sway specific environment
[ -f "${WAYLAND_CONFIG_HOME}/env" ] && {
    set -a
    # shellcheck disable=SC1090
    . "${WAYLAND_CONFIG_HOME}/env"
    set +a
}

# Reference implementation:
# /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
# exec /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1

# swc-launch is used in preference to dbus
swc=$(which swc-launch)
command -v "$swc" > /dev/null 2>&1 && {
    exec swc-launch -t /dev/tty7 -- /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
} || {
    dbus=$(which dbus-run-session)
    command -v "$dbus" > /dev/null 2>&1 && {
        # dbus-launch --sh-syntax --exit-with-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1
        exec dbus-run-session /usr/bin/sway -d > ${WAYLAND_CONFIG_HOME}/.autolauncher.log 2>&1 &
    }
}
