#! /bin/sh
# Initialize the environment variables/flags/repositories

alias /='eval'
alias //='lineno="$LINENO"'

SCRIPT_NAME="kiss-env" && export SCRIPT_NAME

# share folder initialization
[ ! -z "${SHARE_PREFIX:+x}" ] || {
	[ -d "/mnt/init" ] &&
	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
		[ -d "/opt/init" ] &&
		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
		printf '%s %s\n' '$SHARE_PREFIX' "not found"
	}
}

_functions="$SHARE_PREFIX/init/functions"
[ ! -f "$_functions" ] && {
	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
	exit 0
} || {
	env_reset_type="$(type "env_reset" > /dev/null 2>&1 && type "env_reset")" || :
	[ ! -z "${env_reset_type:+x}" ] ||
		. "$_functions"
}

# : "${LOGNAME:="$(id -nu)"}" && export LOGNAME
// env_reset LOGNAME "$(id -nu)"

KISS_PATH=''

// env_reset SHARE_PREFIX_DEV "/opt"

: "${REPO_ROOT:="/var/db/kiss"}" && export REPO_ROOT
: "${REPO_ROOT_DEV:="$SHARE_PREFIX_DEV/${REPO_ROOT#*/}"}" && export REPO_ROOT_DEV

[ -z "${KISS_DEBUG+x}" ] || {
	# Later ones have higher priority
	if [ -z "${KISS_PATH:+x}" ]; then
		KISS_PATH=$REPO_ROOT/kiss-repo-repos
	else
		KISS_PATH=$REPO_ROOT/kiss-repo-repos:$KISS_PATH
	fi

	KISS_PATH=$REPO_ROOT/repos/flatpak/flatpak:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/cemkeylan/personal:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/cemkeylan/editors:$KISS_PATH

	KISS_PATH=$REPO_ROOT/repos/containers:$KISS_PATH

	KISS_PATH=$REPO_ROOT/repos/eudaldgr/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/libs:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/garbage:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/gfx:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/java:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/lxqt:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/office:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/python:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/science:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/themes:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/eudaldgr/video:$KISS_PATH

	KISS_PATH=$REPO_ROOT/repos/periish/audio:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/cmd-utils:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/containers:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/dbus:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/misc:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/ricing:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/periish/xfce4:$KISS_PATH

	KISS_PATH=$REPO_ROOT/noir/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/noir/testing:$KISS_PATH
	KISS_PATH=$REPO_ROOT/noir/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/noir/core:$KISS_PATH

	KISS_PATH=$REPO_ROOT/sauzer/xorg:$KISS_PATH
	KISS_PATH=$REPO_ROOT/sauzer/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/sauzer/core:$KISS_PATH

	KISS_PATH=$REPO_ROOT/dm/im:$KISS_PATH
	KISS_PATH=$REPO_ROOT/dm/kernel:$KISS_PATH
	KISS_PATH=$REPO_ROOT/dm/site:$KISS_PATH

	KISS_PATH=$REPO_ROOT/repos/fonts/kiss-fonts:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/himmalerin/modified:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/himmalerin/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/desktop:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/xorg:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/dumpsterfire/core:$KISS_PATH

	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/bin:$KISS_PATH
	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/community:$KISS_PATH
	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/kiss-somethingsomethingstatic/core:$KISS_PATH

	# KISS_PATH=$REPO_ROOT/repo/wayland:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/repo/testing:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/repo/extra:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/repo/core:$KISS_PATH

	# KISS_PATH=$REPO_ROOT/repos/mmatongo:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/jedahan:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/ioraff/modified:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/ioraff/dbus:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/ioraff/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/games/equipment:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/games/games:$KISS_PATH

	# KISS_PATH=$REPO_ROOT/repos/lang:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/lang/testing:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/lang/languages:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/lang/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/talyn:$KISS_PATH

	KISS_PATH=$REPO_ROOT/kiss-repo/dbus:$KISS_PATH
	KISS_PATH=$REPO_ROOT/kiss-repo/extra:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/kiss-repo/modified:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/kiss-repo/old:$KISS_PATH

	KISS_PATH=$REPO_ROOT/repos/community/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/community/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/repos/community/core:$KISS_PATH

	# KISS_PATH=$REPO_ROOT/glasnost/modules/community/community:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/wayland:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/extra:$KISS_PATH
	# KISS_PATH=$REPO_ROOT/glasnost/modules/repo/core:$KISS_PATH

	KISS_PATH=$REPO_ROOT/community/community:$KISS_PATH
	KISS_PATH=$REPO_ROOT/boost/community:$KISS_PATH
	KISS_PATH=$REPO_ROOT/wyverkkiss/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/wyverkkiss/gnu:$KISS_PATH
	KISS_PATH=$REPO_ROOT/wyverkkiss/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/wyverkkiss/core:$KISS_PATH

	KISS_PATH=$REPO_ROOT/dilyn/wayland:$KISS_PATH
	KISS_PATH=$REPO_ROOT/dilyn/gpl:$KISS_PATH
	KISS_PATH=$REPO_ROOT/dilyn/extra:$KISS_PATH
	KISS_PATH=$REPO_ROOT/dilyn/core:$KISS_PATH

	if [ -z "${KISS_PATH:+x}" ]; then
		KISS_PATH=$REPO_ROOT/kiss-llvm
	else
		KISS_PATH=$REPO_ROOT/kiss-llvm:$KISS_PATH
	fi

}


# : "${REPO_MAIN="$REPO_ROOT/lm"}" && export REPO_MAIN
# Whatever folder name you'd like to use
// env_reset REPO_MAIN "$REPO_ROOT/rolling"
# This is the real REPO_MAIN
# Link to a local development repo root
# Actually it is a recommended way to avoid maintaining a seperate repo
repo_main_source="$REPO_ROOT_DEV/lm"

newline="
"
repo_main() {

	# local kiss_root="${1:?"Fake root can not be empty"}"
	# Empty means the local host
	local kiss_root="${1-}"
	local repo_main_target="$kiss_root/${REPO_MAIN#*/}"
	[ -d "$kiss_root/${REPO_ROOT#*/}" ] ||  \mkdir -p "$kiss_root/${REPO_ROOT#*/}"

	[ ! -e "$repo_main_source" ] &&
		printf '%s %s\n' '$repo_main_source' "'$repo_main_source' [for $kiss_root/${REPO_MAIN#*/}] does not exist" ||
	[ -d "$repo_main_target" ] || {
		[ -L "$repo_main_target" ] ||
		[ -h "$repo_main_target" ]
	} || {
		[ "$(readlink -fn "$REPO_ROOT")" != "$(readlink -fn "$REPO_ROOT_DEV")" ] || {
			printf '%s %s\n' '$REPO_ROOT' "'$REPO_ROOT' has local settings and can not be same as '$REPO_ROOT_DEV'"
			printf '%s %s\n' '$LAYOUT_INIT' "'$LAYOUT_INIT' has the details"
			# exit 1
			return 0
		}
		[ ! -L "$repo_main_target" ] &&
		\ln -sf "$repo_main_source" "$repo_main_target" ||
		[ "$(readlink -fn "$repo_main_target")" = "$(readlink -fn "$repo_main_source")" ] || {
			\rm -f "$repo_main_target" || {
				printf '%s %s\n' '$REPO_ROOT/rolling' "'$REPO_ROOT/rolling' modification failed"
				# exit 1
				return 0
			}

			\ln -sf "$repo_main_source" "$repo_main_target"
		}
	}
}

repo_main

if [ -z "${KISS_PATH:+x}" ]; then
	KISS_PATH=$REPO_MAIN/extra
else
	KISS_PATH=$REPO_MAIN/extra:$KISS_PATH
fi

KISS_PATH=$REPO_MAIN/fonts:$KISS_PATH
KISS_PATH=$REPO_MAIN/wayland:$KISS_PATH
KISS_PATH=$REPO_MAIN/system:$KISS_PATH
KISS_PATH=$REPO_MAIN/core:$KISS_PATH

# Static version will remove dynamic libraries
# KISS_PATH=$REPO_MAIN/static/bin:$KISS_PATH
# KISS_PATH=$REPO_MAIN/static/community:$KISS_PATH
# KISS_PATH=$REPO_MAIN/static/wayland:$KISS_PATH
# KISS_PATH=$REPO_MAIN/static/extra:$KISS_PATH
# KISS_PATH=$REPO_MAIN/static/core:$KISS_PATH

export KISS_PATH

# : "${ARCH:="x86_64"}" && export ARCH
// env_reset ARCH "x86_64"
# : "${KISS_XHOST_ARCH:="$ARCH"}" && export KISS_XHOST_ARCH
// env_reset KISS_XHOST_ARCH "$ARCH"
# : "${KISS_XBUILD_ARCH:="$KISS_XHOST_ARCH"}" && export KISS_XBUILD_ARCH
// env_reset KISS_XBUILD_ARCH "$KISS_XHOST_ARCH"
# : "${CLIBC:="musl"}" && export CLIBC
// env_reset CLIBC "musl"
# : "${KISS_XHOST_ABI:="$CLIBC"}" && export KISS_XHOST_ABI
// env_reset KISS_XHOST_ABI "$CLIBC"
# : "${KISS_XBUILD_ABI:="$KISS_XHOST_ABI"}" && export KISS_XBUILD_ABI
// env_reset KISS_XBUILD_ABI "$KISS_XHOST_ABI"
# : "${KISS_XHOST_TRIPLE:="$KISS_XHOST_ARCH-linux-$KISS_XHOST_ABI"}" && export KISS_XHOST_TRIPLE
// env_reset KISS_XHOST_TRIPLE "$KISS_XHOST_ARCH-linux-$KISS_XHOST_ABI"
# : "${KISS_XBUILD_TRIPLE:="$KISS_XBUILD_ARCH-linux-$KISS_XBUILD_ABI"}" && export KISS_XBUILD_TRIPLE
// env_reset KISS_XBUILD_TRIPLE "$KISS_XBUILD_ARCH-linux-$KISS_XBUILD_ABI"
# For aports
# : "${CARCH:="$ARCH"}" && export CARCH
// env_reset CARCH "$ARCH"
# : "${CTARGET_ARCH:="$ARCH"}" && export CTARGET_ARCH
// env_reset CTARGET_ARCH "$ARCH"
# For cports
# : "${CHOST:="${KISS_XHOST_TRIPLE}"}"	 && export CHOST
// env_reset CHOST "${KISS_XHOST_TRIPLE}"
# : "${CTARGET:="${KISS_XHOST_TRIPLE}"}" && export CTARGET
// env_reset CTARGET "${KISS_XHOST_TRIPLE}"
# : "${CBUILD:="${KISS_XBUILD_TRIPLE}"}" && export CBUILD
// env_reset CBUILD "${KISS_XBUILD_TRIPLE}"

# If you insist to update local system
# KISS_ROOT= && export KISS_ROOT
# Or if unset, kiss package manager will set it to '/'
# [ -z "${KISS_ROOT+x}" ] || unset KISS_ROOT
#
# By default use a target address (/opt/kiss or /mnt/kiss)
# /mnt/kiss might be a mount point of /dev/nvme0n1p3 ... something
# /opt/kiss normally has larger size (20 GB is recommended) on plain local filesystem
# Thiese two values are put to prevent from ruining local systemm by accident
export KISS_ROOT="/opt/kiss" BOOTSTRAP=
[ -d "$KISS_ROOT" ] || \mkdir -p "$KISS_ROOT"

repo_main "$KISS_ROOT"

# : "${KISS_REMOTE_REPO="$KISS_PATH"}" && export KISS_REMOTE_REPO
// env_reset KISS_REMOTE_REPO "$KISS_PATH"
# https://github.com/glasnostlinux/glasnost/releases
# CFLAGS="-march=x86-64 -mtune=generic -pipe -Os"
# CFLAGS="--target=$KISS_XHOST_TRIPLE -Os -fPIC -no-pie"
# CFLAGS="--target=$KISS_XHOST_TRIPLE -Os -pipe -fPIC -mtune=native --host=x86_64"
# CFLAGS="--target=$KISS_XHOST_TRIPLE -Os -fPIC -mcpu=x86-64"
# : "${CFLAGS:="--target=$KISS_XHOST_TRIPLE -O3 -pipe -fPIC -march=x86-64 -mtune=native"}" && export CFLAGS
// env_reset CFLAGS "--target=$KISS_XHOST_TRIPLE -O3 -pipe -fPIC -march=x86-64 -mtune=native"
# : "${CXXFLAGS="$CFLAGS"}" && export CXXFLAGS
// env_reset CXXFLAGS "$CFLAGS"
# : "${CPPFLAGS="$CXXFLAGS"}" && export CPPFLAGS
// env_reset CPPFLAGS "$CXXFLAGS"

# : "${MAKEFLAGS:="-j $(($(nproc) + 1))"}" && export MAKEFLAGS
// env_reset MAKEFLAGS "-j $(($(nproc) + 1))"

[ -z "${KISS_PROMPT+x}" ] || unset KISS_PROMPT
# export KISS_PROMPT=0
# export KISS_TMPDIR="/tmp/$(/usr/bin/whoami)/kiss"
# [ -d "$KISS_TMPDIR" ] || \mkdir -p "$KISS_TMPDIR"
# : "${DEST_ROOT:="/working/kiss"}" && export DEST_ROOT
: ${DEST_ROOT:="/working/kiss"} && export DEST_ROOT

[ -d "$DEST_ROOT" ] || \mkdir -p "$DEST_ROOT"
# git config --global --add safe.directory "$DEST_ROOT"
# : "${REPO_BASE:="$REPO_MAIN/base"}" && export REPO_BASE
// env_reset REPO_BASE "$REPO_MAIN/base"




