#! /bin/sh

SCRIPT_NAME="xdg-runtime-dir" && export SCRIPT_NAME

[ ! -z "$(type "env_reset" > /dev/null && type "env_reset")" ] &&
[ ! -z "${SHARE_PREFIX:+x}" ] ||
{
	[ -f "/mnt/init/include/route" ] &&
	. /mnt/init/include/route
} || {
	printf '%s %s\n' '$env_reset' "'$env_reset' could not get defined"
	exit 0
}

case "${id-} ${os_name-} ${os_pretty_name-}" in *"kiss"*)
	IS_KISS= && export IS_KISS
esac

[ -z "${IS_KISS+x}" ] || export DONT_USE_GREET=

# : ${UID="$(id -u)"} && export UID
// env_reset UID "$(id -u)"
[ -n "${UID:+x}" ] || printf '%s %s\n' '$UID' "${UID-}"

# : "${LOGNAME:="$(id -nu)"}" && export LOGNAME
// env_reset LOGNAME "$(id -nu)"
# : "${HOME:="$(/usr/bin/awk -F : -v v="${LOGNAME}" \
#   "\$1 == v {print \$6}" /etc/passwd)"}" && export HOME
// env_reset HOME "$(/usr/bin/awk -F : -v v="${LOGNAME}" \
	"\$1 == v {print \$6}" /etc/passwd)"

# home="$(/usr/bin/awk -F ":" -v v="${LOGNAME}" "\$1 == v {print \$6}" /etc/passwd)"
# [ "$home" = "$HOME" ] || {
#     HOME="$home"
#     export HOME
#     echo "Fixed \$HOME = $HOME"
# }
[ -n "${LOGNAME:+x}" ] ||
printf '%s %s\n' '$LOGNAME' "${LOGNAME-}"
[ -n "${HOME:+x}" ] ||
printf '%s %s\n' '$HOME' "${HOME-}"

# : ${XDG_DATA_HOME:="$HOME/.local/share"} && export XDG_DATA_HOME
// env_reset XDG_DATA_HOME "$HOME/.local/share"
[ -d "${XDG_DATA_HOME}" ]   || doas \mkdir -p "${XDG_DATA_HOME}"

# : ${XDG_CACHE_HOME:="$HOME/.cache"} && export XDG_CACHE_HOME
// env_reset XDG_CACHE_HOME "$HOME/.cache"
[ -d "${XDG_CACHE_HOME}" ]  || doas \mkdir -p "${XDG_CACHE_HOME}"

# : ${XDG_CONFIG_HOME:="$HOME/.config"} && export XDG_CONFIG_HOME
// env_reset XDG_CONFIG_HOME "$HOME/.config"
[ -d "${XDG_CONFIG_HOME}" ] || doas \mkdir -p "${XDG_CONFIG_HOME}"

# expect_xdg_runtime_dir="/run/user/$UID"
# [ "${XDG_RUNTIME_DIR}" = "$expect_xdg_runtime_dir" ] ||
# # [ ! -z "${XDG_RUNTIME_DIR+x}" ] || {
# #
# : ${XDG_RUNTIME_DIR="/run/user/$UID"} && export XDG_RUNTIME_DIR
# [ "${XDG_RUNTIME_DIR}" = "$expect_xdg_runtime_dir" ] ||
# XDG_RUNTIME_DIR="/run/user/$UID" && export XDG_RUNTIME_DIR
// env_reset XDG_RUNTIME_DIR "/run/user/$UID"

# [ "${XDG_RUNTIME_DIR}" = "$expect_xdg_runtime_dir" ] ||
# printf '%s %s\n' '$XDG_RUNTIME_DIR' "$XDG_RUNTIME_DIR"

[ -d "${XDG_RUNTIME_DIR}" ] || doas \mkdir -p "${XDG_RUNTIME_DIR}"

group_name="$UID"
case "$(id $LOGNAME)" in *"users"*)
	group_name="users"
esac
# [ "$(stat -L -c '%u' "$XDG_RUNTIME_DIR")" = "$UID" ] ||
[ "$(\ls -dl "$XDG_RUNTIME_DIR" | awk '{print $3}')" = "$UID" ] ||
	doas chown -R $UID:$group_name "${XDG_RUNTIME_DIR}"

# perm="$(stat -L -c '%A' "$XDG_RUNTIME_DIR")"
# [ "$(stat -L -c '%A' "$XDG_RUNTIME_DIR")" = "drwx------" ] ||
[ "$(\ls -dl "$XDG_RUNTIME_DIR" | awk '{print $1}')" = "drwx------" ] ||
	doas chmod 0700 "${XDG_RUNTIME_DIR}"

# [ "$DBUS_SESSION_BUS_ADDRESS" = "unix:path=$XDG_RUNTIME_DIR/bus" ] ||
# : ${DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"} &&
# export DBUS_SESSION_BUS_ADDRESS
// env_reset DBUS_SESSION_BUS_ADDRESS "unix:path=$XDG_RUNTIME_DIR/bus"

[ ! -z "${DONT_USE_GREET+x}" ] ||
[ -z "$(id -u "_greeter" 2> /dev/null)" ] || {
	[ -d "/var/cache/tuigreet" ] ||
	doas \mkdir -p /var/cache/tuigreet
	doas /usr/bin/chown -R _greeter:_greeter /var/cache/tuigreet
	doas /usr/bin/chmod 0755 /var/cache/tuigreet
	# doas \mkdir -p /var/lib/_greeter
	# doas /usr/bin/chown -R _greeter:_greeter /var/lib/_greeter
	# doas /usr/bin/chmod 0755 /var/lib/_greeter
}


# }
