#! /bin/sh
#
# header() {
newline="
"
alias /='eval'
alias //='lineno="$LINENO"'

# SCRIPT_NAME="$1" && export SCRIPT_NAME

# share folder initialization
[ ! -z "${SHARE_PREFIX:+x}" ] || {
	[ -d "/mnt/init" ] &&
	{ SHARE_PREFIX="/mnt" && export SHARE_PREFIX; } || {
		[ -d "/opt/init" ] &&
		{ SHARE_PREFIX="/opt" && export SHARE_PREFIX; } ||
		printf '%s %s\n' '$SHARE_PREFIX' "not found"
	}
}

_functions="/usr/include/kiss/functions"
[ -f "$_functions" ] ||
_functions="$SHARE_PREFIX/init/include/functions"
[ ! -f "$_functions" ] && {
	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
	exit 0
} || {
	env_reset_type="$(type "env_reset" > /dev/null && type "env_reset")" || :
	[ ! -z "${env_reset_type:+x}" ] ||
		. "$_functions"
}
# }

# header "$@"
