#! /bin/sh
#
# header() {
newline="
"
alias /='eval'
alias //='lineno="$LINENO"'

# share folder initialization
[ ! -z "${DOT_CONFIG:+x}" ] || {
	[ -d "/mnt/init" ] &&
	{ DOT_CONFIG="/mnt" && export DOT_CONFIG; } || {
		[ -d "/opt/init" ] &&
		{ DOT_CONFIG="/opt" && export DOT_CONFIG; } ||
		printf '%s %s\n' '$DOT_CONFIG' "not found"
	}
}

_functions="/usr/include/kiss/func"
[ -f "$_functions" ] ||
_functions="$DOT_CONFIG/include/func"
[ ! -f "$_functions" ] && {
	printf '%s %s\n' '$_functions' "'$_functions' does not exist"
	exit 0
} || {
	env_reset_type="$(type "env_reset" > /dev/null && type "env_reset")" || :
	[ ! -z "${env_reset_type:+x}" ] ||
		. "$_functions"
}
# }

# header "$@"
